### PR TITLE
Add support for secured websocket (mandatory in Chrome since version 47)

### PR DESCRIPTION
**Pull request by SergeAx**

### CODE REVIEW

**Comment by shanet** [comment]
Awesome, thanks. I'll take a look at this this week.

**Comment by Globik** [comment]
This is all an old stuff. Then the webrtc promise based api is by now. So it does not work properly. Update all that.

**Comment by shanet** [comment]
Globik, do you have an example of that I can merge or reference?

**Comment by Globik** [comment]
@shanet  oh no, for the time being I am struggling over it on my comp in chrome browser v-50. But according https://www.w3.org/TR/webrtc/#simple-peer-to-peer-example 
here is some solution for peer to peer promise based.

**Comment by Globik** [comment]
Yes, here it is 
https://github.com/mdn/samples-server/tree/master/s/webrtc-from-chat
Websocket signal channel, text chat with a chance to invite a chatter to webrtc video audio session. All is a romise based api

**Comment by shanet** [comment]
@Globik thanks for the tip. I've moved this example to use promises in 76cac6ea218c254ce1319693b5e05306d412d8b2.

@SergeAx It took a bit longer than I hoped, but I finally got time to finish up merging the secure websockets implementation. Thanks!

**Pull request merged**
